setting:
  localpath: E:/qq
  name: boot1

#==================== 网络请求 okhttp3 配置  ============================  

#==================== 数据库  连接池 mybatis 配置  ============================  
spring:
   thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    #     新版本不支持content-type: text/html，故新写法
    servlet:
      content-type: text/html
 
   datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/boot1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: 123456
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
   redis:
    host: 127.0.0.1
    port: 6379
#    password: alaley
    database: 0
    timeout: 10000  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1
        # 最大活跃连接数，负数为不限制
        max-active: -1 
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:/mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.study.boot1.bean  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#==================== TOMCAT  ============================
server:
  port: 8089
  servlet:
    context-path: /${setting.name}
  max-http-header-size: 0
#设置Tomcat编码
#server.tomcat.uri-encoding=UTF-8
# tomcat最大线程数，默认为200
  tomcat:
    max-connections: 500
    max-http-post-size: 0
    max-threads: 800
    min-spare-threads: 0
# tomcat的URI编码
    uri-encoding: UTF-8
##### 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹（如：C:\Users\Shanhy\AppData\Local\Temp）
####server.tomcat.basedir=/Users/weimy/tmp/springboot_log/tomcat-tmp
# 打开Tomcat的Access日志，并可以设置日志格式的方法：
#server.tomcat.access-log-enabled=true
#server.tomcat.access-log-pattern=
# accesslog目录，默认在basedir/logs
#server.tomcat.accesslog.directory=
    accesslog:
      buffered: true
      directory: ${setting.localpath}/log/${setting.name}
      enabled: true
      file-date-format: .yyyy-MM-dd
      #pattern: common
      pattern: "%h %l %u %t %T %r %s %b %{Referer}i %{User-Agent}i %{X-Requested-With}i %{passport}c"
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

    session:
      # Session timeout. If a duration suffix is not specified, seconds is used.
      timeout: 1800
#==================== LOG  ============================      
logging:
  config: classpath:log4j2.yml   
      